package com.myspace.noticebusinessrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Action implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String actionCode;
	private java.lang.Integer actionID;
	private java.lang.String actionName;
	private java.lang.Short generalTypeID;
	private java.lang.Boolean includeAction;
	private java.lang.Integer noticeTypeID;
	private java.lang.Short programID;

	public Action() {
	}

	public java.lang.String getActionCode() {
		return this.actionCode;
	}

	public void setActionCode(java.lang.String actionCode) {
		this.actionCode = actionCode;
	}

	public java.lang.Integer getActionID() {
		return this.actionID;
	}

	public void setActionID(java.lang.Integer actionID) {
		this.actionID = actionID;
	}

	public java.lang.String getActionName() {
		return this.actionName;
	}

	public void setActionName(java.lang.String actionName) {
		this.actionName = actionName;
	}

	public java.lang.Short getGeneralTypeID() {
		return this.generalTypeID;
	}

	public void setGeneralTypeID(java.lang.Short generalTypeID) {
		this.generalTypeID = generalTypeID;
	}

	public java.lang.Boolean getIncludeAction() {
		return this.includeAction;
	}

	public void setIncludeAction(java.lang.Boolean includeAction) {
		this.includeAction = includeAction;
	}

	public java.lang.Integer getNoticeTypeID() {
		return this.noticeTypeID;
	}

	public void setNoticeTypeID(java.lang.Integer noticeTypeID) {
		this.noticeTypeID = noticeTypeID;
	}

	public java.lang.Short getProgramID() {
		return this.programID;
	}

	public void setProgramID(java.lang.Short programID) {
		this.programID = programID;
	}

	public Action(java.lang.String actionCode, java.lang.Integer actionID,
			java.lang.String actionName, java.lang.Short generalTypeID,
			java.lang.Boolean includeAction, java.lang.Integer noticeTypeID,
			java.lang.Short programID) {
		this.actionCode = actionCode;
		this.actionID = actionID;
		this.actionName = actionName;
		this.generalTypeID = generalTypeID;
		this.includeAction = includeAction;
		this.noticeTypeID = noticeTypeID;
		this.programID = programID;
	}

}